services:
  inventory.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_HTTP_PORTS=27511
     - ASPNETCORE_HTTPS_PORTS=27512
    ports:
     - "27511:27511"
     - "27512:27512"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro